const frames = [
  "Next.js",
  "React",
  "Angular",
  "svelte",
  "C",
  "C++",
  "C#",
  "Rust",
];
export const list = [
  [
    "make a cookie clicker clone",
    "make a idle game",
    "make a tic tac toe game",
    "make a snake game",
    "make a hangman game",
    "make a memory game",
    "make a sudoku game",
    "make a simulator game",
    "make a rpg game",
    "make an online game",
    "make a game for kids",
    "make a game for adults",
    "make a game for teens",
    "make a game for seniors",
    "make a learning game",
    "make a puzzle game",
    "make a word game",
    "make a crossword game",
    "make a trivia game",
    "make a game of your choice",
    "make a party game",
    "make a mobile game",
    "make a desktop game",
    "make a browser game",
    "make a web game",
    "make a shooter game",
    "make a racing game",
    "make a sports game",
    "make a strategy game",
    "make a card game",
    "make a board game",
    "make a dice game",
    "make a math game",
    "make a logic game",
    "make a programming game",
    "make a language game",
    "make a music game",
    "make a simulation game",
    "make a strategy game",
    "make a war game",
    "make a word game",
    "make a maze game",
    "make a puzzle game",
    "make a brain game",
    "make a game to kill time",
    "build a game in next.js",
    "build a game in svelte",
    "build a game in react",
    "build a game in angular",
    "build a game in vanilla js, html, and css",
    "build a game with tailwind",
    "build a game with C",
    "build a game with C++",
    "build a game with rust",
    "build a game with C#",
    "build a clone of a game you play",
  ],
  [
    "build a image processing app",
    "build a chat app",
    "build a to-do list app",
    "build a note-taking app",
    "build a file manager app",
    "build a calendar app",
    "build a contacts app",
    "build a messaging app",
    "build a music player app",
    "build a video player app",
    "build a productivity app",
    "build a task manager app",
    "build a personal organizer app",
    "build a project management app",
    "build a time tracker app",
    "build a weather app",
    "build a currency converter app",
    "build a calculator app",
    "build a timer app",
    "build a stopwatch app",
    "build a clock app",
    "build a alarm app",
    "build a timer app",
    "build a stopwatch app",
    "build a idea generator app",
    "build a mind map app",
    "build a diagram app",
    "build a flowchart app",
    "build a bar chart app",
    "build a pie chart app",
    "build a line chart app",
    "build a scatter plot app",
    "build a histogram app",
    "build a heat map app",
    "build a tree map app",
    "build a network graph app",
    "build a map app",
    "build a graph app",
    "build a spreadsheet app",
    "build a database app",
    "build a database manager app",
    "build a data visualization app",
    "build a data analysis app",
    "build a data processing app",
    "build a financial app",
    "build a budgeting app",
    "build a expense tracker app",
    "build a invoicing app",
    "build a accounting app",
    "build a banking app",
    "build an HR app",
    "build an employee management app",
    "build an HR management app",
    "build an employee scheduling app",
    "build an expense management app",
    "build an invoice management app",
    "build a payroll app",
    "build a HR analytics app",
    "build an app to fix a problem you have",
    "build an app in next.js",
    "build an app in svelte",
    "build an app in react",
    "build an app in angular",
    "build an app in vanilla js, html, and css",
    "build an app with tailwind",
    "build an app with C",
    "build an app with C++",
    "build an app with rust",
    "build an app with C#",
    "build a clone of an app you use",
  ],
];
