export const list = [
    [
        "make a cookie clicker clone",
        "make a idle game",
        "make a tic tac toe game",
        "make a snake game",
        "make a hangman game",
        "make a memory game",
        "make a sudoku game",
        "make a simulator game",
        "make a rpg game",
        "make an online game",
        "make a game for kids",
        "make a game for adults",
        "make a game for teens",
        "make a game for seniors",
    ],
    [
        "build a image processing app",
        "build a chat app",
        "build a to-do list app",
        "build a note-taking app",
        "build a file manager app",
        "build a calendar app",
        "build a contacts app",
        "build a messaging app",
        "build a music player app",
        "build a video player app",
        "build a productivity app",
        "build a task manager app",
        "build a personal organizer app",
        "build a project management app",
        "build a time tracker app",
        "build a weather app",
        "build a currency converter app",
        "build a calculator app",
        "build a timer app",
        "build a stopwatch app",
        "build a clock app",
        "build a alarm app",
        "build a timer app",
        "build a stopwatch app",
    ],
];